# Generated by Django 3.0.3 on 2020-02-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200226_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
